plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'java'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven { name = 'Fabric'; url = 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraft_version', project.minecraft_version
    inputs.property 'loader_version', project.loader_version
    inputs.property 'fabric_version', project.fabric_version

    filesMatching('fabric.mod.json') {
        expand(
            version: project.version,
            minecraft_version: project.minecraft_version,
            loader_version: project.loader_version,
            fabric_version: project.fabric_version
        )
    }
}

jar {
    archiveBaseName = project.archives_base_name
    archiveVersion = project.mod_version
    archiveClassifier = '26.2'
}
